# .streamlit/secrets.toml

[connections.snowflake]
account = "https://ab62604.ap-south-1.aws.snowflakecomputing.com/"
user = "NEHA"
password = "Neha@123"
role = "DATA_ENGINEER"
warehouse = "COMPUTE_WH"
database = "RAW"
schema = "DELAY_SCHEMA"
client_session_keep_alive = true